server:
  port: 6002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.101:8089  #nginx 集群版nacos 3333  4444 5555
management:
  endpoints:
    web:
      exposure:
        include: "*"