server:
  port: 6002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.101:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"