server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:qingfengyunfei16/cloudDemo.git
           #搜索目录
          search-paths:
            - springcloud-config
      #读取分支
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka #集群版