server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.101:3333
    sentinel:
      transport:
        #配置 Sentinel Dashboard 地址
        dashboard: 192.168.79.101:8080
        #默认8719端口，如被占用则自动+1直至找到未被占用端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.79.101:3333
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: "*"