server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.101:3333
    sentinel:
      transport:
        #配置 Sentinel Dashboard 地址
        dashboard: 192.168.79.101:8080
        #默认8719端口，如被占用则自动+1直至找到未被占用端口
        port: 8719
# 消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider
