server:
  port: 80
eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: false
    #表示是否从EurekaServer抓取已有的注册信息 默认为true
    #单节点无所谓 集群必须设置为true 才能配合ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:9001/eureka  单机版
      defaultZone: http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka #集群版
#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状态正常的情况下，两端连接所用时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用时间
  ConnectTimeout: 5000
logging:
  level:
    #feign 日志以什么级别监控什么接口
    com.yunfan.springcloud.service.PaymentFeignService: debug